# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    container_name: cuicuisine-server
    build:
      context: .
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - server-database
    environment:
      - MONGO_ALIAS=mongodb
      - MONGO_PORT=27017
      - ENV=production
      - LOGLEVEL=${LOGLEVEL}
      - LOGDIRPATH=${LOGDIRPATH}
    volumes:
      - ${STORAGE}:/app/storage/:rw
      - ${LOGDIRPATH}:/app/logs/:rw
      # - server-data:/app/storage
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/app/ca/:ro
    develop:
      watch:
        - action: rebuild
          path: .

  server-database:
    image: mongo:${MONGOVERS}
    container_name: mongodb
    command: ["mongod", "--config", "/etc/mongodb.conf/mongodb.conf"]
    ports:
      - 27018:27017
    volumes:
      - ${DB}/data:/data/db:rw # Persist MongoDB data
      - ${DB}/config/:/etc/mongodb.conf/:ro # Mount MongoDB configuration file
  
  # certbot:
  #   image: certbot/certbot:latest
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw


